import React,{useState}from'react';import{createRoot}from'react-dom/client';import'./styles/global.css';
const themes=[['carbon','Carbon Gold'],['storm','Storm Steel'],['arctic','Arctic Ledger'],['inferno','Inferno Pro'],['ocean','Ocean Glass'],['forest','Forest Work'],['neon','Neon Grid'],['classic','Classic Light']];
const admin=['Dashboard','Clients','Employes','Sous-traitants','Chantiers','Devis','Contrats','Factures','Catalogue','Comptabilite','Statistiques','Recompenses','IA','Reglages'];
const staff=['Punch','Breaks','Calendrier','Statistiques','Profil','Factures','Recompenses'];
const details={Dashboard:['Revenus','Factures a recevoir','Chantiers actifs','Employes actifs'],Clients:['Fiche client','Adresse','Telephone','Email'],Employes:['Profil','Taux','Deductions','Avantages'],Factures:['PDF','Signature tactile','Logo','Envoi email texto'],Recompenses:['Objectifs employe','Objectifs equipe','Objectifs chantier','Souper ou tirage'],Profil:['Info personnelle','Info compagnie','Logo','Documents'],Comptabilite:['Revenus','Depenses','Recus photo','Paiements'],Statistiques:['Graphiques','Profit chantier','Heures','Production']};
const days=['Conge','Tres petite','Petite','Demi','Normale','Grosse','Tres grosse','Explosive'];
function App(){const[mode,setMode]=useState('admin');const[tab,setTab]=useState('Dashboard');const[theme,setTheme]=useState('carbon');const tabs=mode==='admin'?admin:staff;function swap(x){setMode(x);setTab(x==='admin'?'Dashboard':'Punch')}return <main className={'shell '+theme}><section className='panel hero'><div><p className='eyebrow'>CodexGPT Gestion</p><h1>Gestion entreprise + employes</h1><p>Plateforme multi-entreprise pour admin, travailleurs, punch, factures, calendrier, statistiques et recompenses.</p></div><div className='row'><button className={mode==='admin'?'active':''} onClick={()=>swap('admin')}>Admin</button><button className={mode==='staff'?'active':''} onClick={()=>swap('staff')}>Employe</button></div></section><section className='panel'><p className='eyebrow'>Themes</p><h2>8 styles</h2><div className='row'>{themes.map(([id,name])=><button className={theme===id?'active':''} onClick={()=>setTheme(id)} key={id}>{name}</button>)}</div></section><section className='appgrid'><aside className='panel'><h2>{mode==='admin'?'Administration':'Employe'}</h2><div className='tabs'>{tabs.map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</div></aside><section className='panel'><p className='eyebrow'>Module</p><h2>{tab}</h2>{tab==='Punch'?<Punch/>:<Module tab={tab}/>}</section></section><section className='panel'><p className='eyebrow'>Onboarding</p><div className='grid'>{['Langue','Pays','Region','Devise','Mentions','Autorisations'].map(x=><div className='card' key={x}>{x}</div>)}</div></section><section className='panel'><p className='eyebrow'>Calendrier</p><div className='calendar'>{days.map((x,i)=><div className={'day d'+i} key={x}>{x}</div>)}</div></section></main>}
function Punch(){const[on,setOn]=useState(false);return <div className='punch'><div className='geo'>Zone chantier 25 m</div><div className='money'>63,00 $ CAD</div><div className='timer'>01:30:00</div><button className={'action '+(on?'danger':'success')} onClick={()=>setOn(!on)}>{on?'Punch out':'Punch in'}</button></div>}
function Module({tab}){let arr=details[tab]||['Formulaire','Donnees entreprise','Roles','Supabase plus tard'];return <div className='grid'>{arr.map(x=><div className='card' key={x}>{x}</div>)}</div>}
createRoot(document.getElementById('root')).render(<App/>);
