import React,{useState}from'react';import{createRoot}from'react-dom/client';import'./styles/global.css';
const themes=['carbon','storm','arctic','inferno','ocean','forest','neon','classic'];
const admin=['Tableau de bord','Clients','Employes','Sous-traitants','Chantiers','Devis','Contrats','Factures','Catalogue','Comptabilite','Statistiques','Recompenses','IA chantier','Reglages'];
const staff=['Punch','Breaks','Calendrier','Statistiques','Profil','Mes factures','Recompenses'];
const setup=['Langue','Pays','Province ou Etat','Devise','Mentions legales','Autorisations','Entreprise'];
const days=['Conge','Tres petite','Petite','Demi-journee','Normale','Grosse','Tres grosse','Explosive'];
function App(){const[mode,setMode]=useState('admin');const[tab,setTab]=useState('Tableau de bord');const[theme,setTheme]=useState('carbon');const[step,setStep]=useState(0);const tabs=mode==='admin'?admin:staff;function setSpace(x){setMode(x);setTab(x==='admin'?'Tableau de bord':'Punch')}return <main className={'shell '+theme}><section className='panel hero'><div><p className='eyebrow'>CodexGPT Gestion</p><h1>Gestion d'entreprise multi-entreprise</h1><p>Une base PWA pour gerer administration, employes, chantiers, factures, punch, calendrier, statistiques, recompenses et IA chantier.</p></div><div className='row'><button className={mode==='admin'?'active':''} onClick={()=>setSpace('admin')}>Application admin</button><button className={mode==='staff'?'active':''} onClick={()=>setSpace('staff')}>Application employe</button></div></section><section className='panel'><p className='eyebrow'>Themes</p><h2>Choisir le visuel</h2><div className='row'>{themes.map(t=><button className={theme===t?'active':''} onClick={()=>setTheme(t)} key={t}>{t}</button>)}</div></section><section className='panel'><p className='eyebrow'>Onboarding international</p><h2>{setup[step]}</h2><div className='row'>{setup.map((x,i)=><button key={x} className={step===i?'active':''} onClick={()=>setStep(i)}>{i+1}. {x}</button>)}</div><div className='checks'><label><input type='checkbox'/> Conditions</label><label><input type='checkbox'/> Confidentialite</label><label><input type='checkbox'/> Localisation</label><label><input type='checkbox'/> Camera et photos</label><label><input type='checkbox'/> Notifications</label></div></section><section className='appgrid'><aside className='panel'><h2>{mode==='admin'?'Administration':'Employe'}</h2><div className='tabs'>{tabs.map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</div></aside><section className='panel'><p className='eyebrow'>Module actif</p><h2>{tab}</h2>{tab==='Punch'?<Punch/>:<Module tab={tab}/>}</section></section><section className='panel'><p className='eyebrow'>Calendrier</p><h2>Legende des journees</h2><div className='calendar'>{days.map((x,i)=><button className={'day d'+i} key={x}><b>{i+1}</b><span>{x}</span></button>)}</div></section></main>}
function Punch(){const[on,setOn]=useState(false);const[pay,setPay]=useState('heure');let amount=pay==='heure'?'63,00 $ CAD':pay==='pi2'?'780,00 $ CAD':'1 000,00 $ CAD';return <div className='punch'><div className='geo'>Dans la zone chantier - rayon 25 m</div><div className='money'>{amount}</div><div className='timer'>01:30:00</div><div className='row'><button className={pay==='heure'?'active':''} onClick={()=>setPay('heure')}>Heure</button><button className={pay==='pi2'?'active':''} onClick={()=>setPay('pi2')}>Pied carre</button><button className={pay==='job'?'active':''} onClick={()=>setPay('job')}>Job</button></div><button className={'action '+(on?'danger':'success')} onClick={()=>setOn(!on)}>{on?'Punch out':'Punch in'}</button></div>}
function Module({tab}){if(tab==='Recompenses')return <div className='grid'><div className='card'>Objectifs par employe</div><div className='card'>Objectifs par equipe</div><div className='card'>Souper, tirage, bonus ou prix</div><div className='card'>Suivi de progression</div></div>;return <div className='grid'><div className='card'>Formulaire {tab}</div><div className='card'>Donnees separees par entreprise</div><div className='card'>Permissions par role</div><div className='card'>Connexion Supabase prevue</div></div>}
createRoot(document.getElementById('root')).render(<App/>);
